### ISSUE TITLE
Format removed when time is changed

### ISSUE THREAD

**Issue by anavarroi** [zhaber/datetimepicker#15]
When you have a datetimepicker with date and hour like the example http://plnkr.co/edit/2JByf4?p=preview with one date format (dd-MM-yyyy) when the user change the hour text box the format of the date is removed. But when you change again the date with the calendar the format is applied.

Furthermore when you try to clean the hours through the ng-model, this means to initialise the model, the time is not cleaned, while the date is cleaned.

And finally, when you apply bootstrap syles to render the size of both componentes (date and hour) seems to be always fixed.

Thank you very much.

**Comment by zhaber** [comment]
Hey, can you describe the detailed steps to reproduce the first issue? As far as the second issue is concerned, the last code change makes it possible to update ng-model hours programmatically: http://plnkr.co/edit/2JByf4?p=preview The last issue is caused by underlying components used by datetime picker, you can find more about them at http://angular-ui.github.io/bootstrap/

**Comment by manuquentin** [comment]
Hello,
I think this is due the angular 1.3, here a [plunkr](http://plnkr.co/edit/xJrOaedC9pB5SE1yW6yH?p=preview) updated to this version.

**Comment by rcdilorenzo** [comment]
I'm seeing this same issue.

**Comment by hoodi** [comment]
One thing that is probably linked with the described behavior.
When using Angular 1.3 the date format is not initialized correctly. Choosing a date from the picker changes the date in the input field to the correct format but if the variable is set to a Javascript Date it's always shown in the default format when the the page is (re)loaded.

**Comment by zhaber** [comment]
Try this plunkr http://plnkr.co/edit/crEULTS4R3DHNPOJ7OkU?p=preview and the latest version of  datetimepicker.js, let me know if you have any issues.

**Comment by rjmackay** [comment]
That change seems to be working for me. Both on plunkr and in my app too
