### ISSUE TITLE
Support for locales?

### ISSUE THREAD

**Issue by sebastialonso** [zhaber/datetimepicker#18]
I'd be glad to implement locale preferences, for example to change the month name from 'January' to 'Enero', or the Today button on the calendar.

Let me see what I can do after I start bothering you :)

**Comment by zhaber** [comment]
Thanks for investing your time in datetimepicker, internationalization would be a quite helpful improvement.

**Comment by martin5211** [comment]
Any news on this feature? Would be great to have i18n support or delegate it to Moment

**Comment by zhaber** [comment]
I will be more than willing to add i18n once datepicker and timepicker are internationalized.  You can find issues related to these two plugins at https://github.com/angular-ui/bootstrap
