### ISSUE TITLE
Default Time

### ISSUE THREAD

**Issue by jdgblinq** [zhaber/datetimepicker#25]
One of the requirements I had this week was to have two dependent datetimepicker fields, one for the start date and one for the end date. Another requirement was to have the end date's time default to 23:59, in order to save some input time, as this is our most common end time for this form.

Also, if the datepicker changes, the time should stay the same.

**Comment by zhaber** [comment]
Thank you for the Pull request, I learned more about angular scopes from it and Default Time seems like a desirable feature to have out of the box. The only concern is code complexity required to implement this functionality (thus maintenance cost), and the fact that usually there is a good date/time default which can be easily set using the model value.

**Comment by jdgblinq** [comment]
I understand.

This also fixes a bug in the main code base, btw. Currently, if you attempt to edit the timepicker value in master's index.html from the browser, you get weird 0's in the field that make it unpleasant to edit. The plunkr in the README doesn't exhibit this behavior. I tracked the problem down to a couple of commits made recently:

https://github.com/zhaber/datetimepicker/commit/8879d51dddb176b849b373bfb87c43f56558e5fb
https://github.com/zhaber/datetimepicker/commit/1c9f271679ae3b749fe0574244f9c151ce276391

And then I engineered a solution.

If you don't take this PR, I understand, but at least be aware of this problem. I think some sort of automated testing solution would be nice in the future. Either protractor or karma or both. When implemented, that will most likely alleviate any additional maintenance overhead.

**Comment by zhaber** [comment]
https://github.com/zhaber/datetimepicker/commit/8879d51dddb176b849b373bfb87c43f56558e5fb allows to modify time in a model object programmatically and make the time inside a datetimepicker input to be updated accordingly (see Reset Hours button in Plunkr). The padding zeros problem was addressed in the last commit.
