### ISSUE TITLE
Create bower release

### ISSUE THREAD

**Issue by szabyg** [zhaber/datetimepicker#27]
It would be great to have bower releases so other projects can rely on this component.

**Comment by zhaber** [comment]
There is actually a bower release 0.11, you can install it by running:
bower install angular-ui-bootstrap-datetimepicker#0.11

**Comment by szabyg** [comment]
v0.11 is a tag of your repository. Bower (the command-line tool) can find and install repository tags. If you try to enter `bower info angular-ui-bootstrap-datetimepicker` at the command line, you'll see the list of versions bower knows of the component. As control you can try the same with angular-ui as package name. I don't exactly know the reason but bower can't resolve your releases, only tags and latest. So bower install angular-ui-bootstrap-datetimepicker#0.11 doesn't work, only with #v0.11.

**Comment by zhaber** [comment]
Added version 0.11.0:

    $ bower info angular-ui-bootstrap-datetimepicker
    ...
    git://github.com/zhaber/datetimepicker.git#0.11.0
    {
      name: 'angular-ui-bootstrap-datetimepicker',
      version: '0.11.0',
      description: 'Date-time picker AngularJS Bootstrap plugin',
      ...
      }
    }
    
    Available versions:
      - 0.11.0
