### ISSUE TITLE
Clear button doesn't clear the time, only the date

### ISSUE THREAD

**Issue by szabyg** [zhaber/datetimepicker#28]
If either the ngModel is set to undefined or the user clicks the clear button, the time fields are still filled.
Tried on [Plunkr](http://plnkr.co/edit/2JByf4?p=preview).

**Comment by zhaber** [comment]
Unfortunately, the current version of angular-ui timepicker used by datetimepicker directive does not support an empty value. You can vote for this issue at https://github.com/angular-ui/bootstrap/issues/1114

**Comment by szabyg** [comment]
Oh, that's a surprise but thanks for the info! I will!

**Comment by ftorghele** [comment]
angular-ui/bootstrap#1114 is now solved

**Comment by gmaggio** [comment]
The current version of angular-ui timepicker can now be cleared. Is it possible now to implement it in this **datetimepicker** plugin?

**Comment by ftorghele** [comment]
it's already merged so it should be part of the next release.
