### ISSUE TITLE
can not  type manually hours or minutes in double digits

### ISSUE THREAD

**Issue by OlhaTodorashko** [zhaber/datetimepicker#30]
When I try to change a value in the hour or minute inputs manually (having a value already there and using backspace to delete one digit) strange side effects occur:

1. I have 22 in the minutes input
2. Hitting backspace from the end of the input (2 should be show)
3. Input updates and shows "02"

If I try to do that again - backspace on the last two digit - I'll get "00" and after that - I cant change the input what so ever. 

Please note that clicking the up and down arrow still works fine.

It looks as the date picker applies date formatting when the backspace is hit ("2" -> "02", "5" -> "05", "0" -> "00").

**Comment by vredchenko** [comment]
Hi Olha. 

It seems that upgrading the dependency to "angular-bootstrap": "0.12.1" fixes the issue.

@zhaber Any chance you might update bower.json for us?

**Comment by zhaber** [comment]
Done
