### ISSUE TITLE
Support for timezones?

### ISSUE THREAD

**Issue by kayhadrin** [zhaber/datetimepicker#31]
Hi there,

Thanks for making and sharing this great angular plugin.

One thing I noted recently is that it does not support the ng-model-options directive.

Initially, I was using a datetime-local input field with `ng-model-options="{timezone: 'UTC'}"` to display an a datetime input field aligned with the UTC timezone.

But now, since this plugin does not support it, it will only display the date object I provide with the local browser timezone setting. 

Would you see this as a good feature to add to this plugin?

**Comment by zhaber** [comment]
Datetimepicker plugin is built on top of [Angular UI datepicker](http://angular-ui.github.io/bootstrap/), and I will be more than glad to add this feature as soon as ui.bootstrap.datepicker starts to support it.

**Comment by ejain** [comment]
See https://github.com/angular-ui/bootstrap/issues/4837

**Comment by tlk** [comment]
Please consider using the moment.js timezone library https://github.com/moment/moment-timezone/ which is based upon the IANA timezone database: https://www.iana.org/time-zones

https://github.com/mishguruorg/angular-timezone-selector does the above but is rather heavy on dependencies (lodash, chosen, jquery)
