### ISSUE TITLE
Setting timezone?

### ISSUE THREAD

**Issue by jjpprob** [zhaber/datetimepicker#36]
Hi,

First time using GitHub, hope this is the right place for this.

I can't find a way of setting a timezone on the datetime picker, can anyone point me in the right direction?

Thanks!

**Comment by mirkoperillo** [comment]
Hi,

I saw a closed issue about, this #31

**Comment by jjpprob** [comment]
Thanks! Sorry, I didn't think to view the closed issues - as I said, I'm new to GitHub.
