### ISSUE TITLE
Linking two date fields

### ISSUE THREAD

**Issue by HeikkiYlipaavalniemi** [zhaber/datetimepicker#39]
Hello,

I have two date fields on the same page, start date and end date.

Do you have any recommended way how to be able to update end date automatically when start date is changed?

I have tried using ng-change and $scope.$watch without luck.

**Comment by zhaber** [comment]
Since the date is an object and not a primitive, you'll need to use object equality when doing watch:

    $scope.$watch("date", function(value) {
        console.log('New date value:' + value);
    }, true);

See the updated demo plnker at http://plnkr.co/edit/2JByf4?p=preview

**Comment by HeikkiYlipaavalniemi** [comment]
Hi,

Thank you for the quick reply.

I also tried with $watch and I am able to update end date if start date is updated. But seems that with watch its not possible to make only one way binding.

So when I also update end date, start date is changing.

**Comment by zhaber** [comment]
Do you have [the dot](http://stackoverflow.com/questions/17606936/angularjs-dot-in-ng-model) in ng-model? If yes, can you point me to a plunker where I can reproduce the issue?

**Comment by HeikkiYlipaavalniemi** [comment]
Example problem here:
http://plnkr.co/edit/JH3gaX3T8ChbVvHUqxBf

I cannot get the $scope.dateEnd to update when $scope.dateStart changes.

**Comment by zhaber** [comment]
In my browser when I change the value of $scope.dateStart,  $scope.dateEnd changes as well (from both javascript and UI). When $scope.dateEnd is changed, the date stays the same.

**Comment by HeikkiYlipaavalniemi** [comment]
Actually it does change the date correctly but not the time. If you change the start time either with the buttons or by editing the field, the end time stays the same.

But date actually works.

Previously I was able to get the time updating but not the date. So this is better but would still be nice if both would update at the same time.

Tested both with Firefox and Chrome.

**Comment by zhaber** [comment]
Angular is using reference equality for the model objects, so try $scope.dateEnd = new Date(value). I also made a change in the code to update time when the model Date object properties changes.

**Comment by HeikkiYlipaavalniemi** [comment]
Thanks!

Now it works like a charm.
