### ISSUE TITLE
Using placeholder with space cause error and breaks datetimepicker

### ISSUE THREAD

**Issue by bkraszewski** [zhaber/datetimepicker#42]
When you set placeholder with space:
placeholder="Discharge date" or placeholder="Some&nbsp;Text"
in browser log i see error:
Error: [$parse:syntax] Syntax Error: Token 'text' is an unexpected token at column 6 of the expression [Some text] starting at [text].

Sample link: http://plnkr.co/edit/bapdtYaNlgNkGrRGRXp4?p=preview

**Comment by zhaber** [comment]
Made the placeholder attribute to be evaluated as a value not a model property. 
Demo with the latest version of datetimepicker: http://plnkr.co/edit/wPrzF0rc9KW9hwUCJhrb?p=preview
