### ISSUE TITLE
showWeeks works wrong in 01.2016

### ISSUE THREAD

**Issue by sclausen** [zhaber/datetimepicker#43]
The picker shows 58 calendar weeks in january 2016. the february though is calculated correctly and the ui.bootstrap version works correctly too.
Here the reproduction. just click on the picker to open it.
http://plnkr.co/edit/ScoshB?p=preview

**Comment by zhaber** [comment]
Try to update to the latest version of angularjs and angular-ui-bootstrap.
Demo: http://plnkr.co/edit/Vp0sdM?p=preview
