### ISSUE TITLE
style problem

### ISSUE THREAD

**Issue by alireza-saberi** [zhaber/datetimepicker#44]
There is some thing wrong in your style sheet
![style](https://cloud.githubusercontent.com/assets/4853299/7875235/420eaa68-0588-11e5-86f1-685953e2bfa6.png)

**Comment by zhaber** [comment]
Does the Datepicker plugin from https://angular-ui.github.io/bootstrap/ work for you?

**Comment by alireza-saberi** [comment]
@zhaber: Yes sir.
![datepicker](https://cloud.githubusercontent.com/assets/4853299/7875738/e4ee19ca-058e-11e5-88a3-aef8bc30238d.png)

**Comment by zhaber** [comment]
Are you using the same bootstrap template version in both cases http://angular-ui.github.io/bootstrap/ui-bootstrap-tpls-0.13.0.js (as in http://plnkr.co/edit/2JByf4?p=preview)? The CSS applied on top of date and time pickers is pretty simple: http://zhaber.github.io/datetimepicker/datetimepicker.css Try to remove the datetimepicker.css import and see whether the calendar is still broken, if it's not, apply rules from datetimepicker.css one by one and find which one of them breaks the widget.
