### ISSUE TITLE
Unable to use validations errors

### ISSUE THREAD

**Issue by azachar** [zhaber/datetimepicker#47]
Hello zhaber!

Thank you for nice component!

I have a question - how can I show a validation error? I want that the input form will have the reddish outline.. usually I use show-errors directive for it which requires to have an input with the name. 

![image](https://cloud.githubusercontent.com/assets/4659019/8141393/64b4e5a2-1166-11e5-807f-df92c031d7a9.png)

I want to have this around datimepicker's input fields.

![image](https://cloud.githubusercontent.com/assets/4659019/8141392/5ce44a0c-1166-11e5-87bd-71fb049e04f4.png)

Thanks for any help regarding this.

**Comment by zhaber** [comment]
Pending on https://github.com/zhaber/datetimepicker/pull/48
